[0m[[0m[31merror[0m] [0m[0mException in thread "zio-fiber-4" java.lang.RuntimeException: (expected '[' got '{')[0m
[0m[[0m[31merror[0m] [0m[0m	at Main$.parseSudoku$$anonfun$1(Main.scala:16)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.ZIO$.fail$$anonfun$1(ZIO.scala:3149)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.ZIO$.failCause$$anonfun$1$$anonfun$1$$anonfun$1(ZIO.scala:3158)[0m
[0m[[0m[31merror[0m] [0m[0m	at <empty>.Main.parseSudoku(Main.scala:16)[0m
[0m[[0m[31merror[0m] [0m[0m	at <empty>.Main.run(Main.scala:33)[0m
[0m[[0m[31merror[0m] [0m[0m	at Main$.parseSudoku$$anonfun$1(Main.scala:16)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.ZIO$.fail$$anonfun$1(ZIO.scala:3149)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.ZIO$.failCause$$anonfun$1$$anonfun$1$$anonfun$1(ZIO.scala:3158)[0m
[0m[[0m[31merror[0m] [0m[0m	at <empty>.Main.parseSudoku(Main.scala:16)[0m
[0m[[0m[31merror[0m] [0m[0m	at <empty>.Main.run(Main.scala:33)[0m
[0m[[0m[31merror[0m] [0m[0mCaused by: java.lang.RuntimeException: (expected '[' got '{')[0m
[0m[[0m[31merror[0m] [0m[0m	at Main$.parseSudoku$$anonfun$1(Main.scala:16)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.ZIO$.fail$$anonfun$1(ZIO.scala:3149)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.ZIO$.failCause$$anonfun$1$$anonfun$1$$anonfun$1(ZIO.scala:3158)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:381)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:504)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:220)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.internal.FiberRuntime.run(FiberRuntime.scala:139)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:1623)[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mrun[0m) Exception in thread "zio-fiber-4" java.lang.RuntimeException: (expected '[' got '{')[0m
[0m[[0m[31merror[0m] [0m[0m	at Main$.parseSudoku$$anonfun$1(Main.scala:16)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.ZIO$.fail$$anonfun$1(ZIO.scala:3149)[0m
[0m[[0m[31merror[0m] [0m[0m	at zio.ZIO$.failCause$$anonfun$1$$anonfun$1$$anonfun$1(ZIO.scala:3158)[0m
[0m[[0m[31merror[0m] [0m[0m	at <empty>.Main.parseSudoku(Main.scala:16)[0m
[0m[[0m[31merror[0m] [0m[0m	at <empty>.Main.run(Main.scala:33)[0m
